# Используем официальный образ Python
FROM python:latest

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /app

# Копируем файл RockPaperScissorsGame.py в рабочую директорию контейнера
COPY RockPaperScissorsGame.py /app

# Указываем команду для запуска Python-скрипта
CMD ["python", "RockPaperScissorsGame.py"]
