# Используем официальный образ Python
FROM python:latest

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /app

# Копируем файл calc.py в рабочую директорию контейнера
COPY calc.py /app

# Запускаем Python-скрипт
CMD ["python", "calc.py"]
